### ISSUE TITLE
プロフ詳細画面に戻るボタンの作成を行う

### ISSUE THREAD

**Issue by ArataniRyosuke** [free-follow/free-follow#19]
## 概要
現状各機能押下時に戻るボタンがなく、ナビゲーションからのみ遷移可能となっている。

## タスク
- frontにてリダイレクトを実装する。
  - プロフ詳細
  - メッセ詳細

**Comment by ArataniRyosuke** [comment]
https://user-images.githubusercontent.com/32292056/156139283-c8aee19d-2d93-44db-a955-426297b7e641.mp4

## 困っている事
現状、「戻る」ボタン押下時に適切なタグ情報が表示されない状況となっている。
- 「通知機能」にて、「いいね」「足あと」いずれかで詳細プロフ表示->「戻る」押下=>何れも「いいね」タブが表示される。
-  「マッチング機能」にて、「マッチング」「メッセージ」いずれかで詳細プロフ表示->「戻る」押下=>何れも「マッチング」タブが表示される。

## 実現したいこと
- 通知機能にて、「足あと」「いいね」何れかで詳細プロフ表示->「戻る」押下=>適切なタグ情報を表示させたい。
- マッチング機能にて、「マッチング」「メッセージ」何れかで詳細プロフ表示->「戻る」押下=>適切なタグ情報を表示させたい。

## 試した事
以下二通りの方法を試し、現状のプルリクでは後者の方法となっている。
-  VueRouterの機能で、「$router.back()」を使用する。
    - 現状、  profile・search・alert,・messageの4つのルートが存在する為、「search」->「alert」->プロフ詳細->戻るボタン=>「search」が表示される。
- 「戻る」押下時$emitでタグ名を渡し、同時にhistory.goで前の画面を再読み込みさせる。
  - mountedした際にtagNameの初期値が読み込まれ、$emitで渡したtagNameが打ち消される形となり、初期値のタグ情報が表示される。

## 質問
- 上記の方法のうち後者を選択している方向性はあっているか。
- 他に適切な方法がある場合その方向性をお教え頂きたい。
- 何故現状のコードで正しく挙動しないのかを知りたい
  - ライフサイクルハック回りの理解がまだ追い付いていない為

**Comment by ArataniRyosuke** [comment]
## 補足
※「tagName」「タグ」で実装してますが、正しくは「tabName」「タブ」ですね。

**Comment by masatam0915** [comment]
> 上記の方法のうち後者を選択している方向性はあっているか。

こちらの方針については問題ないと思います。ただhistory.goでの再読み込みは必要ですか？tabNameを渡してあげて、渡されたtabNameをもとに表示させれませんか？

>  何故現状のコードで正しく挙動しないのかを知りたい

mountedではなくcreatedを使用しても状況変わりませんか？
https://qiita.com/ksh-fthr/items/2a9f173c706ef6939f93
